### ISSUE TITLE
winserver 2016 x64 无法正常使用 zblog

### ISSUE THREAD

**Issue by nineaiyu** [zblogcn/zblogasp#36]
出现cpu很高，页面打开很慢，建议兼容下新环境

**Comment by zsxsoft** [comment]
PHP版本多少？MySQL版本多少？是哪个进程CPU高？w3wp.exe还是php-cgi.exe还是mysql.exe？

**Comment by nineaiyu** [comment]
使用的是asp，4G4cpu 的，系统是winserver2016  , w3wp.exe CPU超过30% ,页面打开特别慢，差不多要1-2分钟。

**Comment by zsxsoft** [comment]
哦，ASP啊，我看错仓库了
Access数据库还是SQL Server，数据量多大？

**Comment by nineaiyu** [comment]
就是刚安装的，用的access数据库

**Comment by nineaiyu** [comment]
刚进去安装界面，就发现页面响应很慢，然后进服务器看到cpu使用率很高，在30%左右

**Comment by zsxsoft** [comment]
其他ASP程序正常吗？

**Comment by nineaiyu** [comment]
其他正常，你可以测试下，就这个程序不正常

**Comment by zsxsoft** [comment]
已了解原因，你到zb_users/c_option.asp里，找到以下代码（在最后）
```asp
For MsgCount=1 To 350
    Call Execute("Dim ZC_MSG" & Right("000"&MsgCount,3))
Next
```

改为
```asp
Dim MsgCount
Dim MsgString
MsgString = ""
For MsgCount=1 To 350
	MsgString = MsgString & vbCrLf & "Dim ZC_MSG" & Right("000"&MsgCount,3)
Next
```

**Comment by zsxsoft** [comment]
或者你可以关闭Windows Defender
